[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10",
    "networkx>=3.4",
    "plotly>=6.1.2",
    "streamlit>=1.46.0",
]
